export interface Transaction {
  id: string
  userId: string
  titulo: string
  cantidad: number
  tipo: "ingreso" | "gasto"
  categoria: string
  fecha: string
}

export const mockTransactions: Transaction[] = [
  {
    id: "1",
    userId: "1",
    titulo: "Salario",
    cantidad: 10000000,
    tipo: "ingreso",
    categoria: "Trabajo",
    fecha: "2024-12-15",
  },
  {
    id: "2",
    userId: "1",
    titulo: "Compra de supermercado",
    cantidad: 600000,
    tipo: "gasto",
    categoria: "Alimentación",
    fecha: "2024-12-14",
  },

  {
    id: "3",
    userId: "2",
    titulo: "Salario mensual",
    cantidad: 12000000,
    tipo: "ingreso",
    categoria: "Trabajo",
    fecha: "2024-12-01",
  },
  {
    id: "4",
    userId: "2",
    titulo: "Café",
    cantidad: 20000,
    tipo: "gasto",
    categoria: "Alimentación",
    fecha: "2024-12-02",
  },
  {
    id: "5",
    userId: "2",
    titulo: "Gasolina",
    cantidad: 240000,
    tipo: "gasto",
    categoria: "Transporte",
    fecha: "2024-12-03",
  },
  {
    id: "6",
    userId: "2",
    titulo: "Freelance - Proyecto web",
    cantidad: 2000000,
    tipo: "ingreso",
    categoria: "Trabajo",
    fecha: "2024-12-04",
  },
  {
    id: "7",
    userId: "2",
    titulo: "Almuerzo restaurante",
    cantidad: 100000,
    tipo: "gasto",
    categoria: "Alimentación",
    fecha: "2024-12-05",
  },
  {
    id: "8",
    userId: "2",
    titulo: "Pago de arriendo",
    cantidad: 3200000,
    tipo: "gasto",
    categoria: "Vivienda",
    fecha: "2024-12-06",
  },
  {
    id: "9",
    userId: "2",
    titulo: "Venta de artículos usados",
    cantidad: 800000,
    tipo: "ingreso",
    categoria: "Otros",
    fecha: "2024-12-07",
  },
  {
    id: "10",
    userId: "2",
    titulo: "Electricidad",
    cantidad: 320000,
    tipo: "gasto",
    categoria: "Servicios",
    fecha: "2024-12-08",
  },
  {
    id: "11",
    userId: "2",
    titulo: "Internet",
    cantidad: 160000,
    tipo: "gasto",
    categoria: "Servicios",
    fecha: "2024-12-09",
  },
  {
    id: "12",
    userId: "2",
    titulo: "Compra de ropa",
    cantidad: 480000,
    tipo: "gasto",
    categoria: "Compras",
    fecha: "2024-12-10",
  },
  {
    id: "13",
    userId: "2",
    titulo: "Cine",
    cantidad: 60000,
    tipo: "gasto",
    categoria: "Entretenimiento",
    fecha: "2024-12-11",
  },
  {
    id: "14",
    userId: "2",
    titulo: "Bonus trabajo",
    cantidad: 1600000,
    tipo: "ingreso",
    categoria: "Trabajo",
    fecha: "2024-12-12",
  },
  {
    id: "15",
    userId: "2",
    titulo: "Farmacia",
    cantidad: 140000,
    tipo: "gasto",
    categoria: "Salud",
    fecha: "2024-12-13",
  },
  {
    id: "16",
    userId: "2",
    titulo: "Gym mensual",
    cantidad: 200000,
    tipo: "gasto",
    categoria: "Salud",
    fecha: "2024-12-14",
  },
  {
    id: "17",
    userId: "2",
    titulo: "Consultoría - Asesoría técnica",
    cantidad: 1200000,
    tipo: "ingreso",
    categoria: "Trabajo",
    fecha: "2024-12-15",
  },
  {
    id: "18",
    userId: "2",
    titulo: "Supermercado",
    cantidad: 720000,
    tipo: "gasto",
    categoria: "Alimentación",
    fecha: "2024-12-16",
  },
  {
    id: "19",
    userId: "2",
    titulo: "Agua",
    cantidad: 120000,
    tipo: "gasto",
    categoria: "Servicios",
    fecha: "2024-12-17",
  },
  {
    id: "20",
    userId: "2",
    titulo: "Regalo",
    cantidad: 200000,
    tipo: "gasto",
    categoria: "Compras",
    fecha: "2024-12-18",
  },
  {
    id: "21",
    userId: "2",
    titulo: "Dividendo inversión",
    cantidad: 400000,
    tipo: "ingreso",
    categoria: "Inversiones",
    fecha: "2024-12-19",
  },

  {
    id: "22",
    userId: "3",
    titulo: "Salario administrativo",
    cantidad: 16000000,
    tipo: "ingreso",
    categoria: "Trabajo",
    fecha: "2024-12-01",
  },
  {
    id: "23",
    userId: "3",
    titulo: "Mantenimiento sistemas",
    cantidad: 800000,
    tipo: "gasto",
    categoria: "Tecnología",
    fecha: "2024-12-10",
  },

  {
    id: "24",
    userId: "4",
    titulo: "Pago de nómina",
    cantidad: 8000000,
    tipo: "ingreso",
    categoria: "Trabajo",
    fecha: "2024-12-01",
  },
  {
    id: "25",
    userId: "4",
    titulo: "Servicios streaming",
    cantidad: 80000,
    tipo: "gasto",
    categoria: "Entretenimiento",
    fecha: "2024-12-15",
  },
]
